### ISSUE TITLE
Test.py issue

### ISSUE THREAD

**Issue by danbergh412** [wildcard329/python#1]
Comments relating to Test.py

**Comment by danbergh412** [comment]
Adam, can you provide me with the requirements for the Test.py program? The problem is that its really hard for me to understand what needs to happen since there is no prompt asking me to do something.

**Comment by wildcard329** [comment]
The test.py program was an exercise on one of the edX courses. The program itself should have been titled 'pay_calculator', but I ran into so many errors writing the program that I eventually copied the program and named it 'test' so I could try different things. The program was not required to take a user input, therefore it didn't "do" anything. Long story short, it was just an exercise and I probably should take it down.
